### model
model_name: qwen2_vl
method: retake
scaling_factor: 4
attn_implementation: "flash_attention_2"
longvideo_kwargs: {
  'frame_chunk_size': 128,
  'chunked_prefill_frames': 32,
  # KVCache compression
  'kvcache_compression': True,
  'kvcache_compression_kwargs': {
    'dynamic_compression_ratio': True,
    'compression_method': 'pivotkv',
    'pos_embed_reforge': True,
    'max_input_length': 32000
  },
}


### dataset
dataset_name: videomme
anno_file: dataset/video_mme/video_mme.json
dataloader_num_workers: 2

### data
sample_fps: 4
max_num_frames: 2048
longsize_resolution: 448

### generate
do_sample: false

### output
output_dir: results/qwen2vl_7b_video_mme_f2048_4fps_r448/retake_pivot-32k
